name: CI

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: sudo apt update && sudo apt upgrade -y && sudo apt install -y libgtk-4-dev libadwaita-1-dev
      - run: cargo fmt --all --check
      - run: cargo check
      - run: cargo clippy --all-features -- -D warnings
  build-flatpak:
    name: "Build Flatpak Bundle"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v7

      - name: Build App Bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: dev.deimoshall.DecryptIt.json
          run-tests: false
          upload-artifact: false
